// Merge worker outputs into data/solution-counts.json and src/core/levels-data.ts.
// Usage: tsx scripts/build-levels.ts <partfile...>
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { PUZZLE_COUNT } from '../src/core/dice';

const LEVELS = 10;
const counts = new Array<number>(PUZZLE_COUNT).fill(-1);
const args = process.argv.slice(2);
if (args.length === 0) {
  // No part files: rebuild from the merged data file.
  (JSON.parse(readFileSync('data/solution-counts.json', 'utf8')) as number[]).forEach((c, i) => { counts[i] = c; });
}
for (const file of args) {
  const part = JSON.parse(readFileSync(file, 'utf8')) as { worker: number; workers: number; counts: number[] };
  part.counts.forEach((c, i) => { counts[part.worker + i * part.workers] = c; });
}
if (counts.includes(-1)) throw new Error('missing seeds');

// Rank by solution count: most solutions = level 1 (easiest), fewest = level 10.
const order = counts.map((c, seed) => [c, seed] as const).sort((a, b) => b[0] - a[0] || a[1] - b[1]);
const levels = new Uint8Array(PUZZLE_COUNT);
order.forEach(([, seed], rank) => { levels[seed] = Math.min(LEVELS, Math.floor((rank / PUZZLE_COUNT) * LEVELS) + 1); });

const bands = Array.from({ length: LEVELS }, (_, i) => {
  const cs = counts.filter((_, seed) => levels[seed] === i + 1);
  const total = cs.reduce((a, b) => a + b, 0);
  return { level: i + 1, puzzles: cs.length, minSolutions: Math.min(...cs), maxSolutions: Math.max(...cs), meanSolutions: Math.round(total / cs.length), totalSolutions: total };
});

// Pack levels (1..10) as nibbles, base64.
const packed = new Uint8Array(Math.ceil(PUZZLE_COUNT / 2));
for (let i = 0; i < PUZZLE_COUNT; i++) packed[i >> 1] |= levels[i] << ((i & 1) * 4);
const b64 = Buffer.from(packed).toString('base64');

mkdirSync('data', { recursive: true });
writeFileSync('data/solution-counts.json', JSON.stringify(counts));
writeFileSync('data/level-bands.json', JSON.stringify(bands, null, 2));
writeFileSync('src/core/levels-data.ts', `// Generated by scripts/build-levels.ts from data/solution-counts.json. Do not edit.
// Level per puzzle seed (1 = most solutions, ${LEVELS} = fewest), two per byte, base64.
export const LEVEL_COUNT = ${LEVELS};
/** Per level: [puzzles, min solutions, max solutions, mean solutions]. */
export const LEVEL_BANDS = ${JSON.stringify(bands.map((b) => [b.puzzles, b.minSolutions, b.maxSolutions, b.meanSolutions]))} as const;
export const TOTAL_SOLUTIONS = ${counts.reduce((a, b) => a + b, 0)};
export const PACKED_LEVELS =
  '${b64}';
`);
console.table(bands);
